DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS states;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS comments;

CREATE TABLE roles
(
   id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   name TEXT NOT NULL UNIQUE

);

CREATE TABLE users
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    login TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    roles_id BIGINT  NOT NULL REFERENCES roles (id) ON DELETE CASCADE
);

CREATE TABLE states
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    status TEXT NOT NULL CHECK  (status IN ('NEW', 'READED', 'CANCELLED', 'SOLVED')),
    active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE categories
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    code NOT NULL CHECK(code > 0)
);

CREATE TABLE items
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    users_id BIGINT  NOT NULL REFERENCES users (id),
    states_id BIGINT NOT NULL REFERENCES states (id),
    categories_id BIGINT NOT NULL REFERENCES categories (id)
);

CREATE TABLE comments
(
     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     comment TEXT NOT NULL,
     items_id BIGINT NOT NULL REFERENCES items (id) ON DELETE CASCADE

);